name: Primeira Pipeline

on:
    push:
        branches: [main]

jobs:

    sonarqube:
      name: SonarQube
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
          with:
            fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
        - name: SonarQube Scan
          uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8.1.0
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    build:
      runs-on: ubuntu-latest
      steps:
        - name: Gerar Artefato ZIP
          run: zip -r pipeline-demo.zip .

        - name: Publicar artefato
          uses: actions/upload-artifact@v4
          with:
              name: codigo-buildado
              path: pipeline-demo.zip  

    teste_qualidade:
        strategy:
            matrix:
                os: [ubuntu-latest , windows-latest, macos-latest]
                python-version: ['3.10', '3.11', '3.12']

        runs-on: ${{ matrix.os }}

        steps:
            - name: Baixar Artefato
              uses: actions/download-artifact@v4
              with:
                name: codigo-buildado

            - name: Extrair artefato
              run: unzip pipeline-demo.zip    

            - name: Configurar Python
              uses: actions/setup-python@v4
              with:
               python-version: ${{ matrix.python-version }}
               cache: 'pip'

            - name: Instalar dependências
              run: pip install -r requirements.txt

            - name: Análise Estática (Linter)
              run: flake8 .  

            - name: Testes Unitários e Cobertura Mínima
              run: pytest --cov=. --cov-fail-under=90   

 
    deploy:
        runs-on: ubuntu-latest
        needs: teste_qualidade

        steps:
        - name: Simular Deploy
          run: echo "Deploy realizado com sucesso!"



